### ISSUE TITLE
missing domain in gmail

### ISSUE THREAD

**Issue by 0ostreamo0** [gfwlist/gfwlist#1362]
*.gstatic.com, Maybe a missing domain in google group?
For i use gmail it failed to access, unless i switch this domain to ss manually

ISP: China Telecom

**Comment by cicku** [comment]
It's in the list, with 4 subdomains as whitelist rule. These four can be accessed in mainland China.

```
@@||connectivitycheck.gstatic.com
@@||csi.gstatic.com
@@||fonts.gstatic.com
@@||ssl.gstatic.com
```

I'm not sure which subdomain of gstatic was the one you encountered with connectivity issue. Please elaborate your details, thanks.

**Comment by 0ostreamo0** [comment]
these domain is not reachable, in my region......am i exceptional?  
![image](https://user-images.githubusercontent.com/7197034/50956853-b5bc3980-14f7-11e9-8754-59aacba91002.png)

[region info]:
`
{
  "country"     : "China",
  "countryCode" : "CN",
  "region"      : "BJ",
  "regionName"  : "Beijing",
  "city"        : "Beijing",
  "district"    : "",
  "zip"         : "",
  "lat"         : 39.9042,
  "lon"         : 116.407,
  "timezone"    : "Asia/Shanghai",
  "isp"         : "ZHAOONE",
  "org"         : "shanghai wexchange network technology Co. Ltd.",
  "as"          : "AS4812 China Telecom (Group)",
  "mobile"      : false,
  "proxy"       : false,
}
`

**Comment by cicku** [comment]
I have no idea about your case, normally all these gstatic URLs will go to Guxiang located in Beijing, China.

You may want to file a complaint to your ISP, since it's accessible in most of regions of China.

If you use some public DNS services from other countries, they might (primarily those knowing Chinese characteristics) resolve these Google domains to IP located over the globe. If you don't know any about what I just said, please post your result of ping `ssl.gstatic.com` in your reply.

Thanks for your patience.

**Comment by 0ostreamo0** [comment]
ok, there might be problem in my company's network, for it's working well when i use 4G, any way, thanks for your reply~
