### ISSUE TITLE
A question about the syntax used in gfwlist

### ISSUE THREAD

**Issue by hubanya** [gfwlist/gfwlist#239]
First of all, thank you very much for providing such a list. I really appreciate your efforts!

I have a question about the syntax used in the list. If I am correct, the gfwlist uses the syntax for AdBlock Plus filter. Then why do we include both items like `domain.com` and `||domain.com` in the list. For example, we have both `zhao.1984.city` and `||zhao.1984.city`. If `domain.com` is matched with any address that contains the literal "domain.com", it automatically contains anything that is matched with `||zhao.1984.city`. Is there any particular reason to do so?

Thank you!

**Comment by cicku** [comment]
`If domain.com is matched with any address that contains the literal "domain.com", it automatically contains anything that is matched with ||zhao.1984.city`

**It doesn't**. Someone asked me about the syntax weeks ago. Again:

GFWList rules originated from ABP, but **NOT** hastily copied. Let's take `zhao.1984.city` as example:

```
zhao.1984.city
||zhao.1984.city
```

`zhao.1984.city` covers HTTP-Only URL cases:

1. You are accessing URL `http://example.com/zhao.1984.city`;
2. You are accessing URL `http://zhao.1984.city`;
3. You are accessing URL `http://xxx.zhao.1984.city` (xxx is the subdomain name, sometimes could be www, it depends on the site admin's settings as www usage is declining);

Plus, `||zhao.1984.city` covers these:

1. You are accessing URL `http://zhao.1984.city`;
2. You are accessing URL `http://xxx.zhao.1984.city`;
3. You are accessing URL `https://zhao.1984.city`;
4. You are accessing URL `https://xxx.zhao.1984.city`;

It's also possible to write rules exhaustively:

```
zhao.1984.city
|https://zhao.1984.city
|https://xxx.zhao.1984.city
```

And this will increase the size of list again. Meanwhile GFW often blocks the domain + subdomains as TIMEOUT by resolving them to invalid IPs, often in Azerbaijan), so if `https://yyy.zhao.1984.city` appears in the future, GFWList can't cover it immediately.

ABP has an [online tool](https://adblockplus.org/en/redundancy_check) to check if rules are useless, however, ABP's mission is not the same as GFWList. Advertisements will come from both HTTP and HTTPS links whereas GFW is unable to crack HTTPS connection without MITM attack. If you attempt to access `http://example.com/zhao.1984.city`, GFW will reset the connection, but when you attempt to access `https://example.com/zhao.1984.city`, GFW only knows that you are connecting to `https://example.com/`, but it doesn't know the exact path, query or fragment, thus it won't reset the connection.

For this example, it's **OK** to revise the rules to:

```
zhao.1984.city
|https://zhao.1984.city
```

Since `zhao.1984.city` doesn't enable www prefix(`www.zhao.1984.city`) or other subdomains(xxx.zhao.1984.city). But for other rules, it may not apply.

**Comment by hubanya** [comment]
@cicku Thank you very much for the detailed explanation. Is it possible to write the syntax rules used in gfwlist in its readme or doc?

**Comment by cicku** [comment]
I will update the Syntax section of wiki in a few days probably.
