### ISSUE TITLE
How to use this list ?

### ISSUE THREAD

**Issue by Qionglu735** [gfwlist/gfwlist#391]
Hi

Can't see any address or IP in the gfwlist.txt

I am using shadowsocks and set the url as ONLINE PAC, seems no working ...

and help ?

**Comment by zzhhbyt1** [comment]
Hi, @Qionglu735 !
If you chose to user the lastest shadowsocks, you can try option `Local PAC` and then `Update Local PAC from GFWList`.
It's not recommended to use online pac with GFWList since this will lead to heavy servers load.
And if my reply solved your question you can close this issue manually.

**Comment by cicku** [comment]
Sorry, GFWList doesn't offer help of 3rd party tools.
