### ISSUE TITLE
Please remove a site

### ISSUE THREAD

**Issue by luweitest** [gfwlist/gfwlist#480]
|http://85.17.73.31/
it seems only a test site.

**Comment by cicku** [comment]
This IP was used by `exhentai.org` to provide erotic images which are inconspicuous. I'm not sure if someone can verify that they no longer use it, please provide details.

**Comment by luweitest** [comment]
Both exhentai.org and http://85.17.73.31/ can be accessed directly. I am
just curious why there's a numerical IP address in the gfwlist.

**Comment by cicku** [comment]
In the past there were several websites using IP instead of domain to circumvent the GFW. Most of them are removed from list, there are, however, some still left in the list.

Back to this one, it was used as serving thumbnails by exhentai around 2015, and it became inaccessible so I added it into GFWList, for now if it's reachable, I will remove it as well.

Exhentai is an undercover website parted from e-hentai and I'm unable to access it because of the intriguing limitation they have deployed. It would be helpful if someone can login and verify whether they still use this IP or not. A screenshot is needed at least.
