### ISSUE TITLE
请求添加wwe.com

### ISSUE THREAD

**Issue by Nexus2018** [gfwlist/gfwlist#669]
直接输入http://www.wwe.com会自动跳转到http://wwe.pptv.com。
多次新建标签页重复输入http://www.wwe.com，几次之后就不会跳转到http://wwe.pptv.com。

直接输入https://www.wwe.com，不会跳转到pptv.com。

但是无论在http://www.wwe.com或者https://www.wwe.com下，视频都无法播放，提示“the video is unavailable for your region”。

**Comment by cicku** [comment]
Symptom: `wwe.com` -> `wwe.cn` -> `wwe.pptv.com`

**Comment by cicku** [comment]
Bypass region check: Proxy `vod.wwe.com`, will be done in the commit.

Note that GFWList intends to handle `wwe.com` with circumspection, for now it is inept to proxy the whole domain. If you insist on browsing contents from English website instead of PPTV, please manually add it to your custom rules.
